services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "1200:1200"
      - "1935:1935"
    environment:
      STREAM_IP: "localhost"
      INTERNAL_STREAM_PORT: "1200"
      EXPOSED_IP: "localhost:3000"
      MAIN_PORT: "3000"
