version: '1.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "8000:8000"
      - "1935:1935"
    environment:
      - HOST_IP=${HOST_IP}
    env_file:
      - .env
