apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtmp2flv-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rtmp2flv
  template:
    metadata:
      labels:
        app: rtmp2flv
    spec:
      containers:
      - name: rtmp2flv
        image: ghcr.io/deep-jiwan/rtmp2flv:beta
        ports:
          - containerPort: 1935
          - containerPort: 1200
          - containerPort: 3000
        env:
          - name: STREAM_IP
            value: "localhost"
          - name: INTERNAL_STREAM_PORT
            value: "1200"
          - name: EXPOSED_IP
            value: "localhost:3000"
          - name: MAIN_PORT
            value: "3000"
